name: Generate Files from Flutter JSON

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Files
        run: |
            python flutter_hash/tools/fetcher.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
            commit_message: Update Flutter hashes
            skip_fetch: true
            skip_checkout: true
            file_pattern: flutter_hash/**
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
